"""add pinned_files

Revision ID: c2fbb800bd8e
Revises: 4163dd6af66a
Create Date: 2025-12-23 14:59:51.424583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2fbb800bd8e'
down_revision: Union[str, Sequence[str], None] = '4163dd6af66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contexts', sa.Column('pinned_files', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contexts', 'pinned_files')
    # ### end Alembic commands ###
